---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order
  namespace: casche

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: order
  namespace: casche
rules:
- apiGroups: ["chaos"]
  resources: ["pods"]
  verbs: ["get"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: order
  namespace: casche
subjects:
- kind: ServiceAccount
  name: order
  namespace: casche
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: order
