kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: order
  namespace: casche
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: order
  namespace: casche
subjects:
- kind: Group
  name: chaos
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: order
