apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-two
  namespace: casche
  labels:
    app: project-two
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-two
  template:
    metadata:
      labels:
        app: project-two
    spec:
      volumes:
      - name: config-casche-p2
        configMap:
          name: fluent-conf
      containers:
      - name: fluentd
        image: grafana/fluent-plugin-loki:latest
        ports:
        - containerPort: 24224
        imagePullPolicy: IfNotPresent
        env:
        - name: LOKI_URL
          value: http://loki:3100
        volumeMounts:
        - name: config-casche-p2
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
      - name: p1-application
        image: sentrurion/casche-project-two:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: casche-credentials
              key: url
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: casche-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: casche-credentials
              key: password
        imagePullPolicy: Always # IfNotPresent
          
